data:
    name: 'patches_dataset'
    dataset: 'coco'  # 'hpatches' 'coco'
    alteration: 'all'  # 'i' 'v' 'all'
    cache_in_memory: false
    validation_size: 100
    preprocessing:
        resize: false  # False for coco
    distort:
        enable: false
model:
    name: 'classical_detectors'
    method: 'fast'  #'harris' 'shi' 'random'
    batch_size: 50  # unused
    learning_rate: 0.001  # unused
    nms: 4
    top_k: 600
eval_iter: 600
seed: 1
